on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Build
        run: |
          brew install automake autoconf libtool pkg-config
          make -j8
      
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            output/curl.xcframework
            output/tatsu.xcframework
            output/plist.xcframework
            output/usbmuxd.xcframework
            output/libimobiledeviceGlue.xcframework
            output/libimobiledevice.xcframework
