on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build
        run: |
          brew install automake autoconf libtool pkg-config
          make -j8
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            output/curl.xcframework.zip
            output/tatsu.xcframework.zip
            output/plist.xcframework.zip
            output/usbmuxd.xcframework.zip
            output/libimobiledeviceGlue.xcframework.zip
            output/libimobiledevice.xcframework.zip
